### ISSUE TITLE
Need for "control-implementations" consolidation based on compliance framework

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns/component-generator#16]
As we use components from various repos each include a starting control-implementations which points to the compliance framework (Currently just NIST 800-53). When we combine these component files this field is duplicated. 

May need to look at sorting/grouping based on control-implementations frameworks for the event we start to map to multiple frameworks.

**Comment by brandtkeller** [comment]
@CloudBeard Can you clarify how to reproduce this issue? I'd like to checkout the duplicate field.

**Comment by CloudBeard** [comment]
I believe this had been fixed in previous PR.

Just double checked and its a non issue for mixing control-implementations (FedRAMP/800-53) using the component-generator.

**Comment by brandtkeller** [comment]
Thanks for verifying. Closing this issue and we can re-open if the issue persists.
